# Generated by Django 6.0 on 2025-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Anmerkungen / Extrawünsche'),
        ),
    ]
