# Generated by Django 6.0.4 on 2026-04-21 09:02

from django.db import migrations, models


def forwards(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='preparing').update(status='topping')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Eingegangen'), ('topping', 'Belegt'), ('ready', 'Abholbereit'), ('completed', 'Ausgegeben')], default='received', max_length=20),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
