# Generated by Django 6.0.4 on 2026-04-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('received', 'Eingegangen'), ('topping', 'Belegt'), ('ready', 'Ofenbereit'), ('completed', 'Ausgegeben'), ('failed', 'Fehlgeschlagen')], default='received', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItemStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Gestartet'), ('ready', 'Ofenbereit'), ('complete', 'Ausgegeben'), ('fail', 'Fehlgeschlagen'), ('reset', 'Zurückgesetzt')], max_length=20)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.orderitem')),
            ],
        ),
    ]
